<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Porter</RootNamespace>
    <AssemblyName>Porter</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>0.2.0</Version>
  </PropertyGroup>

</Project>
